controller_list:
  - name: fake_manipulator_1_controller
    joints:
      - 1joint_s
      - 1joint_l
      - 1joint_e
      - 1joint_u
      - 1joint_r
      - 1joint_b
      - 1joint_t
  - name: fake_manipulator_2_controller
    joints:
      - 2joint_s
      - 2joint_l
      - 2joint_e
      - 2joint_u
      - 2joint_r
      - 2joint_b
      - 2joint_t
  - name: fake_dual_manipulator_controller
    joints:
      - 1joint_s
      - 1joint_l
      - 1joint_e
      - 1joint_u
      - 1joint_r
      - 1joint_b
      - 1joint_t
      - 2joint_s
      - 2joint_l
      - 2joint_e
      - 2joint_u
      - 2joint_r
      - 2joint_b
      - 2joint_t