controller_list:
  - name: fake_sia5d_controller
    joints:
      - 1joint_s
      - 1joint_l
      - 1joint_e
      - 1joint_u
      - 1joint_r
      - 1joint_b
      - 1joint_t
  - name: fake_ur5_controller
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_sia5d_ur5_dual_controller
    joints:
      - 1joint_s
      - 1joint_l
      - 1joint_e
      - 1joint_u
      - 1joint_r
      - 1joint_b
      - 1joint_t
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint